private_origins:
  # Develop.
  - ^http://localhost:\d+$
  # Preview.
  - ^https://pingcap-ossinsight-preview-pr-.+\.surge\.sh$
  - ^https*://.+\.preview\.app\.github\.dev/*$
  # Production.
  - ^https://ossinsight\.io$
  - ^https://live\.ossinsight\.io$
  # Next
  - ossinsight-next.vercel.app
  - ossinsight-next-ui.vercel.app
public_origins:
  # External Users.
  - ^https://github1s\.com$
  - ^https://github\.com$
