name: Verify Query Definition

on:
  pull_request:
    paths:
      - 'configs/queries/**'
      - 'packages/types/**'

defaults:
  run:
    shell: bash
    working-directory: packages/types

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9.6.0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.json

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile --strict-peer-dependencies

      - name: Verify Query Definition
        run: pnpm run validate:query
