name: Verify Collection Configs

on:
  pull_request:
    paths:
      - 'configs/collections/**'

defaults:
  run:
    shell: bash
    working-directory: packages/cli

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Verify Collection Configs
        run: pnpm run cli:collection:verify
